adds download to yml

diff --git a/.github/workflows/myAction.yml b/.github/workflows/myAction.yml
--- a/.github/workflows/myAction.yml
+++ b/.github/workflows/myAction.yml
@@ -30,3 +30,12 @@ jobs:
               with:
                   name: output
                   path: ./data
+
+            - name: Download New CSV
+              run: |
+                if curl -o data/new-data.csv <replace_this_URL>; then
+                    echo "CSV download successful."
+                else
+                    echo "CSV download failed."
+                    exit 1
+                fi
